# Omarchy's install/omarchy-base.packages (v4.0.4), mapped to nixpkgs attributes.
# Packages Omarchy enables as services (sddm, docker, bluez, cups, ...) are set in
# autarchy.nix instead. Not ported, Arch- or Omarchy-specific: aether asdcontrol
# cliamp expac herdr kernel-modules-hook omacalc omacut omawrite omarchy-nvim
# pacman-contrib ttfx tensaku tobi-try yay.
pkgs: with pkgs; [
  alsa-utils
  bash-completion
  bat
  bluez
  bluez-tools
  brightnessctl
  btop
  chromium
  clang
  cups-filters
  cups-pk-helper
  ddcutil
  docker-buildx
  docker-compose
  dosfstools
  dotnet-runtime
  dua
  evince
  exfatprogs
  eza
  fakeroot
  fastfetch
  fd
  ffmpegthumbnailer
  fontconfig
  foot
  fzf
  git
  gnome-disk-utility
  gnome-themes-extra
  gpu-screen-recorder
  grim
  gum
  hyprland-preview-share-picker
  hyprpicker
  hyprsunset
  imagemagick
  imv
  inetutils
  inotify-tools
  inxi
  jq
  kdePackages.kdenlive
  lazydocker
  lazygit
  less
  libpq
  libreoffice
  libsecret
  libyaml
  llvm
  localsend
  lua5_1
  luarocks
  man-db
  mariadb.client
  mise
  moonlight-qt
  mpv
  mpvScripts.mpris
  nautilus
  nautilus-python
  neovim
  obs-studio
  obsidian
  pamixer
  pinta
  plocate
  python3Packages.poetry-core
  python3Packages.pygobject3
  qrencode
  qt6.qtimageformats
  quickshell
  ripgrep
  ruby
  slurp
  socat
  starship
  sushi
  system-config-printer
  tesseract
  tldr
  tmux
  tree-sitter
  tzupdate
  udiskie
  unzip
  usage
  vips
  whois
  wireless-regdb
  wl-clipboard
  wtype
  xdg-terminal-exec
  xournalpp
  yaru-theme
  yt-dlp
  zbar
  zoxide
  hyprland-qtutils
]
